### ISSUE TITLE
keycloak quarkus version has no "auth" prefix in path

### ISSUE THREAD

**Issue by warmanton** [gogatekeeper/gatekeeper#179]
# Title
keycloak quarkus version has no "auth" prefix in path

## Summary
Cannot configure kecloak without "auth" prefix

## Environment
Version of everything that it's running in your environment:
- OS: docker
- Go (e.g. go version): go version go1.18.3 linux/amd64
- Server (e.g. Keycloak or any other IdP): keycloak (quay.io/keycloak/keycloak:18.0.2)
- Gatekeeper: commit 0821c70ed27e527bafc14b183b0d90dfc3aed0cc (HEAD -> master, tag: 1.5.0, origin/master, origin/HEAD)

## Expected Results

--discovery-url=https://kc.example.com:8443/realms/realm1 (in old versions of KC url should be https://kc.example.com:8443/auth/realms/realm1)

should work in both cases

## Actual Results

gogatekeeper wants "auth" prefix in path

## Steps to reproduce

start gogatekeeper with keycloak:18.0.2

## Additional Information

```diff --git a/config.go b/config.go
index f7c0ff8..2d5b9b1 100644
--- a/config.go
+++ b/config.go
@@ -595,7 +595,7 @@ func (r *Config) updateDiscoveryURI() error {
 func (r *Config) updateRealm() error {
        path := strings.Split(r.DiscoveryURI.Path, "/")
 
-       if len(path) != 4 {
+       if len(path) != 3 {
                return fmt.Errorf("missing realm in discovery url?")
        }
```

the first check patch. Works but after enabling `--enable-forwarding=true` got error:
```
2022-07-13T10:08:18.700Z        error   problem getting PAT token       {"error": "404 Not Found: RESTEASY003210: Could not find resource for full path: https://kc.example.com:8443/auth/realms/realm1/protocol/openid-connect/token"}
```
cannot find where "auth" is inserted.

**Comment by p53** [comment]
https://github.com/Nerzal/gocloak/issues/346

**Comment by djessich** [comment]
I have the same problem. Without using `/auth` in discovery URL, gatekeeper does not start. Please provide a fix for that, as Keycloak 17 changed its default context path and this software is not conform anymore.

**Comment by p53** [comment]
@djessich there is workaround for that as mentioned in issue i posted above https://github.com/Nerzal/gocloak/issues/346#issuecomment-1143207855

**Comment by djessich** [comment]
@p53 So the solution you mean is to change back the context URL for Quarkus distribution with `bin/kc.[sh|bat] start-dev --http-relative-path /auth` ?

**Comment by p53** [comment]
@djessich yes

**Comment by djessich** [comment]
@p53 depends on the Helm chart you're using. I use `codecentric/keycloakx` and there is an option for this, so this isn't a problem. The developers also set it to `/auth` for compatibility reasons.

```
http:
  relativePath: '/auth'
```

However, in the past I also changed that for the legacy Wildfly distribution to `/`, because I did not understand why Keycloak is served under an additional subcontext that does not bring any benefit, except making the URL longer. So I also changed that in the Helm chart.

As I'm experimenting with the gatekeeper Helm chart now and I want to try gatekeeper out, I may need to change that back to `/auth` and change all application configs so those find my Keycloak instance after changing the context path.

**Comment by p53** [comment]
@djessich yeah that /auth is redundant, i added that nerzal library dependency because i wanted to add keycloak authorization funcionality which would require several new calls to keycloak and processing so it was faster to use that library but it has prons that fixing issues like this will take longer/more work

**Comment by djessich** [comment]
@p53 Completely understand that, why reinventing the wheel.

**Comment by maksimkurb** [comment]
@p53 New [12.0.0](https://github.com/Nerzal/gocloak/releases/tag/v12.0.0) release of Gocloak library includes a [fix for this issue](https://github.com/Nerzal/gocloak/issues/346)

**Comment by p53** [comment]
Yup, i had to also made some commits to gocloak to speed up merging that change in gocloak. I would like to make new gatekeeper release this or next week hopefully
