### ISSUE TITLE
SkipTokenVerification should completely skip token verification

### ISSUE THREAD

**Issue by p53** [gogatekeeper/gatekeeper#29]
# Title

SkipTokenVerification should completely skip token verification

## Summary 

SkipTokenVerification should completely skip token verification.

Right now, it gets the access token from request and parses it the token as a JWT (Oauth spec according spec doesn't assume access token must be JWT) and checks if the access token is expired.

## Why?

If we completely skip token verification, users who have authorization servers providing different types of access tokens will be able to use this flag.

## How

Refactor `authenticationMiddleware`.

**Comment by p53** [comment]
@ackerleytng @statik @fredbi what do you think?

**Comment by ackerleytng** [comment]
I updated the issue with as I understand it, please correct it if my understanding is not correct.

`SkipTokenVerification` was meant to be for testing only, and I think the logic is rather difficult to follow, because it is distributed over a few places in the code.

I feel that if we want to allow people to use alternative types of access tokens, we should be supporting other means of verification, instead of asking people to use `SkipTokenVerification` as a feature.

I think that we should in fact remove this option or make what it is skipping more precise.

**Comment by p53** [comment]
i had typo in title..., what i can see from code it is effectively used only in authenticationMiddleware for veryfing access token, with turning of verification we would completely leave on user how he would like to verify access token and they could use our proxy in combination with some other software to verify access token in incoming requests right away (maybe they already have some solution prepared and we are effectively stopping them to use our proxy because of this), later we can add several options for verification but this would be quite big task to make it cleanly and properly so users would need to wait quite a lot of time for this

**Comment by ackerleytng** [comment]
I'm okay to go ahead if @statik or @fredbi are for fully skipping token verification, or if any users chime in to request this.

The original developers must have had their reasons for retaining the functionality for checking expiration but skipping other verification, because it would have been easier to skip verification completely.

There might exist some users who are, like you suggested, using gatekeeper to just validate expiration, but are validating the rest of the JWT using their own software, and changing the definition of this flag would reduce their security. (If there are any users relying on this flag to validate expiration, please chime in on this issue!)
