### ISSUE TITLE
[Support]: How to use gogatekeeper as API backend authentication proxy

### ISSUE THREAD

**Issue by bvidovic1** [gogatekeeper/gatekeeper#340]
Hi all,

I am using gogatekeeper for several application frontends as an authentication proxy. It is connected with Keycloak which is using Microsoft AD as an identity provider.

I am seeking help to see if it is possible to use gogatekeeper as authentication proxy for API backend which has no frontend. I would like that users are able to get token and use that token when sending the requests to the API. Basically, as for my other frontend apps, I would like to externalize and centralize authentication.

Do I need to get token from keycloak directly, or it can be done via gogatekeeper?
How to pass token to the gatekeeper in curl command for example?

Is this even possible?

**Comment by p53** [comment]
Hi, if you want to protect api you must use --no-redirects option on api side, on client side there are several options: 1. you can retrieve token short lived token manually and pass it in auhorization header 2. you can have long live token so that you dont need to fetch it regularly 3. you can use gogatekeeper as forward proxy on client side e.g. as side car to your client app (or e.g. for personal use, users can run it on their workstation), this mode will regularly fetch token from keycloak and then insert it in headers, you need to use -x option for curl or e.g.HTTP_PROXY env var for your client app

**Comment by bvidovic1** [comment]
Hi,

Thank you for your answer. I would like to avoid any potential action on the client/customer side. I would like to configure everything on the server side, to have gogatekeeper and my API bound together.

Basically, I can use gogatekeeper as a sidecar container in the same pod with my API and just make sure that  `--no-redirects=true` option is there. 

Then I can tell users to query for short-lived access_token towards keycloak with client_credentials and username and pass or via authorization_code and use that access token in the request header when communicating via my API. That way I can even provide granular access for certain groups. 

Does this sound ok? :) Is there maybe a better approach on getting the token?

How do I fetch long-lived tokens? Is it just a matter of changing token expiration in keycloak settings or there is something else?


I apologize for asking many questions and thank you in advance for any potential answer.

**Comment by p53** [comment]
You could use offline tokens. From my point of view would be running gatekeeper as forwarding proxy on user side more comfortable and secure
