### ISSUE TITLE
[Update to 2.9.1] ID token signed with an unsupported algorithm

### ISSUE THREAD

**Issue by ZPascal** [gogatekeeper/gatekeeper#394]
# [Update to 2.9.1] ID token signed with an unsupported algorithm

## Summary

Hi @p53, after the update to 2.9.1, I'm facing an issue with the ID token and the proxy mentioned that the signature algorithm is not supported. I'm running Keycloak with default settings and I've already tried to adjust the client settings and signature algorithm on the Keycloak side to a listed algorithm (error message). After changing the algorithm the issue persists. The corresponding error occurs after the update from Gatekeeper version 2.9.0 to 2.9.1. Do you have changed something related to the signature algorithm?

## Environment
- OS: Debian 10 Buster
- Kernel: Linux 4.19.0-24-amd64
- Go: 1.20
- Server: Keycloak 23.0.1 (behind an Apache2 reverse proxy)
- Gatekeeper: 2.9.1

## Expected Results

The calls should work as expected and deliver the same result as with version 2.9.0 of the gatekeeper.

## Actual Results

```log
refresh token failed verification {"error": "invalid token signature\noidc: id token signed with unsupported algorithm, expected [\"PS384\" \"ES384\" \"RS384\" \"ES256\" \"RS256\" \"ES512\" \"PS256\" \"PS512\" \"RS512\"] got \"HS256\""}
```

**Comment by p53** [comment]
@ZPascal fixed issue, please try 2.9.2-rc1

**Comment by ZPascal** [comment]
I've tested the pre-release and can confirm that the solution does not work.

**Comment by p53** [comment]
@ZPascal @bogbert could you please provide cmd line options which are you using?

**Comment by p53** [comment]
ok, tried now, i see, hmm interesting why it wasn't catched by e2e tests, will have to look more closely on this, seems keycloak is using HS256 algorithm for refresh token signature not RS256 and it cannot be changed, probably they wanted this as another layer of security

**Comment by p53** [comment]
ok seems like module used for token verification doesn't support HS256

**Comment by p53** [comment]
also see why it wasn't catched by e2e, refresh tokens were not enabled, i though that they are, will add that option there

**Comment by bogbert** [comment]
I found an interesting post:  https://keycloak.discourse.group/t/rs256-for-refresh-tokens/6849
According to mbonn's reply, Gatekeeper doesn't have to check the refresh token signature. This signature is produced by Keycloak and is only meant to be checked by Keycloak itself, that's why they can use HS256 (an algorithm with a symmetric key), and that's why libraries such as go-oidc don't support HS256.

**Comment by p53** [comment]
@bogbert @p53 you can try 2.9.3-rc1, i checked manually and also added e2e, should be fine

**Comment by p53** [comment]
@bogbert this seems to be different issue, didn't touch these things, do you have idp session check on?

**Comment by p53** [comment]
@bogbert ok see where is the problem, idp session check is now on by default...but seems problem is in underlying library, it is provider method, we correctly set provider options and insecure skip verify to true but this method ignores any settings in provider, quite unexpected, will need to check on library code if this was intentional for some reason or it is just bug

**Comment by p53** [comment]
@bogbert you can try 2.9.3-rc2, that should do the trick, i didn't have time to setup/test it manually, will add tests later when i have time
