### ISSUE TITLE
Error 403 after changing OIDC provider

### ISSUE THREAD

**Issue by mcejp** [gogatekeeper/gatekeeper#70]
## Summary

After using Gatekeeper with a certain OIDC provider for a while, and then reconfiguring it to use a different provider (e.g. a different instance of Keycloak), existing session cookies become "poisonous" and the users are no longer able to access the application.

## Environment

- Server (e.g. Keycloak or any other IdP): Keycloak
- Gatekeeper: 1.3.0 under Docker

## Expected Results

- A log-in page is shown when trying to access the protected resource

## Actual Results

- A blank page is returned with HTTP code 403
- Upon deleting cookies for the domain, login is possible again

## Steps to reproduce

1. Configure Gatekeeper with a certain OIDC provider (OLD_PROVIDER)
2. Log in to the protected application
3. Reconfigure Gatekeeper with another OIDC provider (NEW_PROVIDER)
4. Try to access the application
5. A blank page is returned with HTTP code 403
6. Relevant log entries:

```
2021-03-28T18:28:04.123Z        debug        src/session.go:56        found the user identity        {"id": "f:XXXX:XXXX", "name": "XXXX", "email": "XXXX", "roles": "XXXX", "groups": ""}
2021-03-28T18:28:04.124Z        error        src/middleware.go:210        access token failed verification        {"client_ip": "XXXX", "error": "oidc: id token issued by a different provider, expected \"NEW_PROVIDER\" got \"OLD_PROVIDER\""}
2021-03-28T18:28:04.124Z        info        src/middleware.go:146        client request        {"latency": 0.001078758, "status": 403, "bytes": 0, "client_ip": "192.168.176.1:36870", "method": "GET", "path": "/"}
```

## Additional Information

The work-around is easy (deleting cookies), but still an inconvenience to innocent users. Is there something that could be done server-side?

Thanks!

**Comment by jangaraj** [comment]
IMHO it is expected error. Token from old IDP from the cookie is received and it's validated against new IDP. Solution can be configurable cookie names instead of constants:
https://github.com/gogatekeeper/gatekeeper/blob/79127acdcab7bd5b4d19b45e7bcac08189779f58/doc.go#L61-L62

Gatekeeper admin will have a option to "invalid" old cookie names with old IDP tokens, when there is a change of IDP. I would say this is very rare user edge case. I'm not sure if any other auth proxies are able to handle this edge case in user friendly way.

**Comment by p53** [comment]
they are configurable, options:

```
	CookieAccessName string `json:"cookie-access-name" yaml:"cookie-access-name" usage:"name of the cookie use to hold the access token"`
	// CookieRefreshName is the name of the refresh cookie
	CookieRefreshName string `json:"cookie-refresh-name" yaml:"cookie-refresh-name" usage:"name of the cookie used to hold the encrypted refresh token"`
```

but that could potentially break application

**Comment by p53** [comment]
> ## Summary
> After using Gatekeeper with a certain OIDC provider for a while, and then reconfiguring it to use a different provider (e.g. a different instance of Keycloak), existing session cookies become "poisonous" and the users are no longer able to access the application.
> 
> ## Environment
> * Server (e.g. Keycloak or any other IdP): Keycloak
> * Gatekeeper: 1.3.0 under Docker
> 
> ## Expected Results
> * A log-in page is shown when trying to access the protected resource
> 
> ## Actual Results
> * A blank page is returned with HTTP code 403
> * Upon deleting cookies for the domain, login is possible again
> 
> ## Steps to reproduce
> 1. Configure Gatekeeper with a certain OIDC provider (OLD_PROVIDER)
> 2. Log in to the protected application
> 3. Reconfigure Gatekeeper with another OIDC provider (NEW_PROVIDER)
> 4. Try to access the application
> 5. A blank page is returned with HTTP code 403
> 6. Relevant log entries:
> 
> ```
> 2021-03-28T18:28:04.123Z        debug        src/session.go:56        found the user identity        {"id": "f:XXXX:XXXX", "name": "XXXX", "email": "XXXX", "roles": "XXXX", "groups": ""}
> 2021-03-28T18:28:04.124Z        error        src/middleware.go:210        access token failed verification        {"client_ip": "XXXX", "error": "oidc: id token issued by a different provider, expected \"NEW_PROVIDER\" got \"OLD_PROVIDER\""}
> 2021-03-28T18:28:04.124Z        info        src/middleware.go:146        client request        {"latency": 0.001078758, "status": 403, "bytes": 0, "client_ip": "192.168.176.1:36870", "method": "GET", "path": "/"}
> ```
> 
> ## Additional Information
> The work-around is easy (deleting cookies), but still an inconvenience to innocent users. Is there something that could be done server-side?
> 
> Thanks!

Hi,

could you provide exact and all options you are using.

**Comment by PraserX** [comment]
@mcejp I was facing similar issue. When I changed Client ID, the behavior was the same. The problem can be solved by deleting cookies. I think it is understandable, just like @jangaraj said. But I agree that it's inconvenienced.

**Comment by p53** [comment]
@mcejp - i would try to make IDP+clients etc.. with same configuration as on old IDP + export keys used for signing tokens from old IDP and import to new keycloak, haven't tried it yet, but it could work - did you try to export config from keycloak and import to new instance https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/export-import.html, but still depends on the options, if you have useStore enabled it may still not work, because in that case gogatekeeper stores refresh tokens in store and will use those instead of those in cookies

**Comment by mcejp** [comment]
@p53 Thanks for your reply!

In fact, my 2 Keycloak instances are running in parallel, it's a bit like staging x production. So sharing keys among them probably wouldn't be right.

However, I wasn't aware of `cookie-access-name` (is it documented somewhere?) -- this seems it could be exactly what I need. I'll give it a try and report back.

**Comment by p53** [comment]
in case you won't share them it could not work, because JWT tokens are signed by them so when you switch instances of IDP, new IDP will have new keys => it will return that token is not valid => gatekeeper will return 403

As i checked it is not in documentation, will fix it, anyway to look on available options you can always check https://github.com/gogatekeeper/gatekeeper/blob/master/doc.go

**Comment by mcejp** [comment]
It seems to work perfectly; with the cookies renamed, the sessions now effectively live in a separate namespace from before.

Maybe I didn't explain myself well, but I don't need to use two Keycloak instances with one Gatekeeper *simultaneously*. It is more of a one-time migration.
